builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - "386"

archives:
  - format_overrides:
      - goos: windows
        format: zip

brews:
  - description: Create a new file from a template.
    tap:
      owner: Ryooooooga
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/Ryooooooga/zouch
    install: bin.install "zouch"
    test: system "#{bin}/zouch", "--version"
