builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: amd64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - description: Create a new file from a template.
    tap:
      owner: Ryooooooga
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/Ryooooooga/zouch
    install: bin.install "zouch"
    test: system "#{bin}/zouch", "--version"
